/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sasha.pkg5a;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import sasha.pkg5a.InvalideRangeException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.*;






/**
 *
 * @author Александра
 */
public class ContactEditorUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContactEditorUI.class.getName());
    private List<RecIntegral> integralRecords; // коллекция для хранения записей (ArrayList для нечетного варианта)
    private DefaultTableModel tableModel; // модель таблицы

    /**
     * Creates new form ContactEditorUI
     */
    
    public ContactEditorUI() {
        initComponents();
        
        // НАСТРОЙКА ТАБЛИЦЫ
        tableModel = new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "верхний предел", "нижний предел", "шаг", "результат"
            }
    ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };
            
            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
    
     jTable1.setModel(tableModel);
    
     // Инициализация коллекции (ArrayList для нечетного варианта)
    integralRecords = new java.util.ArrayList<>();
    
    // Сохраняем ссылку на модель таблицы
    tableModel = (DefaultTableModel) jTable1.getModel();
    
    // НАСТРОЙКА ЦВЕТОВ
    java.awt.Color buttonBg = new java.awt.Color(188, 179, 209);
    java.awt.Color textColor = new java.awt.Color(138, 134, 149);
    java.awt.Color fieldBg = new java.awt.Color(217, 207, 226);
    
    // Настройка полей ввода
    jTextFieldLowerLabel.setBackground(fieldBg);
    jTextFieldLowerLabel.setForeground(textColor);
    
    jTextFieldLowerInput.setBackground(fieldBg);
    jTextFieldLowerInput.setForeground(textColor);
    
    jTextFieldStepInput.setBackground(fieldBg);
    jTextFieldStepInput.setForeground(textColor);
    
    // Настройка кнопок
    jButtonAdd.setBackground(buttonBg);
    jButtonAdd.setForeground(textColor);
    jButtonAdd.setFocusPainted(false);
    
    jButtonSolve.setBackground(buttonBg);
    jButtonSolve.setForeground(textColor);
    jButtonSolve.setFocusPainted(false);
    
    jButtonDelete.setBackground(buttonBg);
    jButtonDelete.setForeground(textColor);
    jButtonDelete.setFocusPainted(false);
    
    // Настройка кнопок (добавить эти строки)
    jButtonAdd1.setBackground(buttonBg);
    jButtonAdd1.setForeground(textColor);
    jButtonAdd1.setFocusPainted(false);

    jButtonAdd2.setBackground(buttonBg);
    jButtonAdd2.setForeground(textColor);
    jButtonAdd2.setFocusPainted(false);
    
    // Настройка таблицы
    jTable1.setBackground(fieldBg);
        jTable1.setForeground(textColor);
        jTable1.setSelectionBackground(new java.awt.Color(220, 218, 237));
        jTable1.setGridColor(buttonBg);
        jTable1.setRowHeight(25);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldFunction = new javax.swing.JTextField();
        jTextFieldLowerLabel = new javax.swing.JTextField();
        jTextFieldLowerInput = new javax.swing.JTextField();
        jTextFieldStepInput = new javax.swing.JTextField();
        jButtonSolve = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonAdd1 = new javax.swing.JButton();
        jButtonAdd2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1SaveTxt = new javax.swing.JMenuItem();
        jMenuItem1Loadtxt = new javax.swing.JMenuItem();
        jMenuItem1SaveBin = new javax.swing.JMenuItem();
        jMenuItem1LoadBin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 218, 237));

        jPanel1.setBackground(new java.awt.Color(220, 218, 237));

        jTextFieldFunction.setBackground(new java.awt.Color(217, 207, 226));
        jTextFieldFunction.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFunction.setForeground(new java.awt.Color(138, 134, 149));
        jTextFieldFunction.setText("  cos(x)");
        jTextFieldFunction.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextFieldLowerInput.addActionListener(this::jTextFieldLowerInputActionPerformed);

        jTextFieldStepInput.addActionListener(this::jTextFieldStepInputActionPerformed);

        jButtonSolve.setBackground(new java.awt.Color(188, 179, 209));
        jButtonSolve.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSolve.setForeground(new java.awt.Color(138, 134, 149));
        jButtonSolve.setText("вычислить");
        jButtonSolve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSolve.setFocusPainted(false);
        jButtonSolve.addActionListener(this::jButtonSolveActionPerformed);

        jButtonAdd.setBackground(new java.awt.Color(188, 179, 209));
        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(138, 134, 149));
        jButtonAdd.setText("добавить");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.setFocusPainted(false);
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jButtonDelete.setBackground(new java.awt.Color(188, 179, 209));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(138, 134, 149));
        jButtonDelete.setText("удалить");
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.setFocusPainted(false);
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jLabel1.setBackground(new java.awt.Color(217, 207, 226));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(138, 134, 149));
        jLabel1.setText("Верхний предел");

        jLabel2.setBackground(new java.awt.Color(217, 207, 226));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(138, 134, 149));
        jLabel2.setText("Нижний предел");

        jLabel3.setBackground(new java.awt.Color(217, 207, 226));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(138, 134, 149));
        jLabel3.setText("Шаг");

        jButtonAdd1.setBackground(new java.awt.Color(188, 179, 209));
        jButtonAdd1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAdd1.setForeground(new java.awt.Color(138, 134, 149));
        jButtonAdd1.setText("очистить таблицу");
        jButtonAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd1.setFocusPainted(false);
        jButtonAdd1.addActionListener(this::jButtonAdd1ActionPerformed);

        jButtonAdd2.setBackground(new java.awt.Color(188, 179, 209));
        jButtonAdd2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAdd2.setForeground(new java.awt.Color(138, 134, 149));
        jButtonAdd2.setText("заполнить из коллекции");
        jButtonAdd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd2.setFocusPainted(false);
        jButtonAdd2.addActionListener(this::jButtonAdd2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdd2)
                            .addComponent(jButtonAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(146, 146, 146))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldLowerInput, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jTextFieldLowerLabel)
                            .addComponent(jTextFieldStepInput))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSolve)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAdd2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSolve)
                    .addComponent(jTextFieldLowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jTextFieldLowerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete)
                    .addComponent(jTextFieldStepInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(89, 89, 89))
        );

        jTable1.setBackground(new java.awt.Color(217, 207, 226));
        jTable1.setForeground(new java.awt.Color(138, 134, 149));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "верхний предел", "нижний предел", "шаг", "результат"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(188, 179, 209));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(220, 218, 237));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1SaveTxt.setText("Сохрнить как текст");
        jMenuItem1SaveTxt.addActionListener(this::jMenuItem1SaveTxtActionPerformed);
        jMenu1.add(jMenuItem1SaveTxt);

        jMenuItem1Loadtxt.setText("загрузить как текст ");
        jMenuItem1Loadtxt.addActionListener(this::jMenuItem1LoadtxtActionPerformed);
        jMenu1.add(jMenuItem1Loadtxt);

        jMenuItem1SaveBin.setText("Сохранить как bin");
        jMenuItem1SaveBin.addActionListener(this::jMenuItem1SaveBinActionPerformed);
        jMenu1.add(jMenuItem1SaveBin);

        jMenuItem1LoadBin.setText("Загрузить как bin ");
        jMenuItem1LoadBin.addActionListener(this::jMenuItem1LoadBinActionPerformed);
        jMenu1.add(jMenuItem1LoadBin);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Обновляет отображение таблицы из коллекции integralRecords
     */
    private void updateTableFromCollection() {
    tableModel.setRowCount(0);
    
    for (RecIntegral record : integralRecords) {
        Object[] row = {
            record.getUpperLim(),  // верхний предел
            record.getLowerLim(),  // нижний предел
            record.getStep(),      // шаг
            String.format("%.6f", record.getResult()) // результат
        };
        tableModel.addRow(row);
    }
}
    private void jTextFieldLowerInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLowerInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLowerInputActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
                                                                                                                                                               
        try {
            String upperText = jTextFieldLowerLabel.getText();    // верхний предел
            String lowerText = jTextFieldLowerInput.getText();    // нижний предел
            String stepText = jTextFieldStepInput.getText();      // шаг
            
            double upper = Double.parseDouble(upperText);
            double lower = Double.parseDouble(lowerText);
            double step = Double.parseDouble(stepText);
            
            RecIntegral record = new RecIntegral(lower, upper, step);
            integralRecords.add(record);
            
            DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
            tModel.addRow(new Object[]{record.getHighLimit(), record.getLowerLim(), record.getStep()});  
            
            // Очищаем поля
            jTextFieldLowerLabel.setText("");
            jTextFieldLowerInput.setText("");
            jTextFieldStepInput.setText("");
            
            JOptionPane.showMessageDialog(this, "Запись добавлена!", "Успех", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Введите корректные числа!\nИспользуйте точку (.) для десятичных дробей.", 
                "Ошибка формата", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ошибка параметров", JOptionPane.ERROR_MESSAGE);
        } catch (InvalideRangeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage() + "\nЗначение: " + e.getInvalidValue(), 
                "Ошибка диапазона", JOptionPane.ERROR_MESSAGE);
        }
    

    


    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
                                              
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow != -1) {
        int confirm = JOptionPane.showConfirmDialog(this, "Удалить выбранную строку?", "Подтверждение", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
            tModel.removeRow(selectedRow);
            
            if (selectedRow < integralRecords.size()) {
                integralRecords.remove(selectedRow);
            }
            
            JOptionPane.showMessageDialog(this, "Строка удалена!", "Успех", JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Выберите строку для удаления!", "Предупреждение", JOptionPane.WARNING_MESSAGE);
    }

 

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolveActionPerformed
                                                                                                                            
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow != -1) {
            try {
                double upper = Double.parseDouble(jTable1.getValueAt(selectedRow, 0).toString());
                double lower = Double.parseDouble(jTable1.getValueAt(selectedRow, 1).toString());
                double step = Double.parseDouble(jTable1.getValueAt(selectedRow, 2).toString());
                
                RecIntegral ri = new RecIntegral(lower, upper, step);
                double integral = ri.calculate(lower, upper, step);
                
                if (selectedRow < integralRecords.size()) {
                    integralRecords.set(selectedRow, ri);
                } else {
                    integralRecords.add(ri);
                }
                
                ri.setResult(integral);
                
                jTable1.setValueAt(String.format("%.6f", integral), selectedRow, 3);
                
                JOptionPane.showMessageDialog(this, "Интеграл вычислен: " + String.format("%.6f", integral), 
                    "Результат", JOptionPane.INFORMATION_MESSAGE);
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ошибка формата данных в таблице!\nИспользуйте точку (.) для десятичных дробей.", 
                    "Ошибка формата", JOptionPane.ERROR_MESSAGE);
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Ошибка параметров", JOptionPane.ERROR_MESSAGE);
            } catch (InvalideRangeException e) {
                JOptionPane.showMessageDialog(this, e.getMessage() + "\nЗначение: " + e.getInvalidValue(), 
                    "Ошибка диапазона", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ошибка при вычислении: " + e.getMessage(), 
                    "Ошибка", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Выберите строку для вычисления!", 
                "Предупреждение", JOptionPane.WARNING_MESSAGE);
        }
    



    
    }//GEN-LAST:event_jButtonSolveActionPerformed

    private void jTextFieldStepInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStepInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStepInputActionPerformed

    private void jButtonAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdd1ActionPerformed
                                                                                      
    int confirm = JOptionPane.showConfirmDialog(this, "Очистить таблицу? Все данные будут удалены.", "Подтверждение очистки", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Очищаем таблицу
        tableModel.setRowCount(0);
        
        // Очищаем коллекцию
        //integralRecords.clear();
        
        // Очищаем поля ввода
        jTextFieldLowerLabel.setText("");
        jTextFieldLowerInput.setText("");
        jTextFieldStepInput.setText("");
        
        JOptionPane.showMessageDialog(this, "Таблица очищена!", "Готово", JOptionPane.INFORMATION_MESSAGE);
    }

    
    }//GEN-LAST:event_jButtonAdd1ActionPerformed

    private void jButtonAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdd2ActionPerformed
                                                                                                                                         
    try {
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.setNumRows(0);
        
         for(RecIntegral item: integralRecords){
            tModel.addRow(new Object[]{
                item.getLowLimit(),
                item.getUpperLim(),
                item.getStep(),
                item.getResult(),
            });
        }
        
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Ошибка ввода! Проверьте, что все поля содержат числа.\nИспользуйте точку (.) для десятичных дробей.", 
            "Ошибка формата", JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Ошибка параметров", JOptionPane.ERROR_MESSAGE);
    }


    
    }//GEN-LAST:event_jButtonAdd2ActionPerformed

    private void jMenuItem1SaveBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1SaveBinActionPerformed
       
        if (integralRecords.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Нет данных для сохранения!");
            return;
        }
        
        JFileChooser f = new JFileChooser();
        javax.swing.filechooser.FileNameExtensionFilter filter = 
            new javax.swing.filechooser.FileNameExtensionFilter("Binary file (*.ser)", "ser");
        f.setFileFilter(filter);
        f.showSaveDialog(this);
        
        File file = f.getSelectedFile();
        if (file == null) return;
        
        if (!file.getPath().endsWith(".ser")) {
            file = new File(file.getPath() + ".ser");
        }
        
        try (ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(file))) {
            out.writeObject(integralRecords);
            JOptionPane.showMessageDialog(this, "Сохранено в: " + file.getName());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Ошибка: " + ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1SaveBinActionPerformed

    private void jMenuItem1SaveTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1SaveTxtActionPerformed
    
    if (integralRecords.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Нет данных для сохранения!", 
            "Предупреждение", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    JFileChooser f = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Text file (*.txt)", "txt");   
    f.setFileFilter(filter);
    f.showSaveDialog(this);  // ← ОШИБКА 1: было null, надо this
    
    File file = f.getSelectedFile();
    
    // ОШИБКА 2: endWith → endsWith (правильное написание)
    // ОШИБКА 3: нужно проверить НЕ заканчивается ли на .txt, а не заканчивается
    if (!file.getPath().endsWith(".txt")) {  // ← исправлено
        file = new File(file.getPath() + ".txt");
    }
    
    // ОШИБКА 4: fales → false (правильное написание)
    // ОШИБКА 5: writer не нужно передавать false, просто удалите , fales
    try (FileWriter writer = new FileWriter(file)) {  // ← исправлено
        // ОШИБКА 6: arrInteg → integralRecords (правильное имя переменной)
        for (RecIntegral o : integralRecords) {  // ← исправлено
            writer.write(o.getLowLimit() + "|" +   // ← лучше использовать | вместо пробела
                         o.getUpperLim() + "|" + 
                         o.getStep() + "|" + 
                         o.getResult() + "\n");
        }
        // ОШИБКА 7: flush() и close() не нужны, try-with-resources закрывает автоматически
        
    } catch (IOException ex) {
        // ОШИБКА 8: showMassageDialog → showMessageDialog (правильное написание)
        JOptionPane.showMessageDialog(this, ex);  // ← исправлено
    }

    }//GEN-LAST:event_jMenuItem1SaveTxtActionPerformed

    private void jMenuItem1LoadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1LoadtxtActionPerformed
    
        JFileChooser f = new JFileChooser();
        javax.swing.filechooser.FileNameExtensionFilter filter = 
            new javax.swing.filechooser.FileNameExtensionFilter("Text file (*.txt)", "txt");
        f.setFileFilter(filter);
        f.showOpenDialog(this);
        
        File file = f.getSelectedFile();
        if (file == null) return;
        
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            List<RecIntegral> loadedRecords = new ArrayList<>();
            String line;
            
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split("\\|");
                if (parts.length >= 3) {
                    double lower = Double.parseDouble(parts[0]);
                    double upper = Double.parseDouble(parts[1]);
                    double step = Double.parseDouble(parts[2]);
                    double result = parts.length >= 4 ? Double.parseDouble(parts[3]) : 0.0;
                    
                    RecIntegral record = new RecIntegral(lower, upper, step);
                    record.setResult(result);
                    loadedRecords.add(record);
                }
            }
            
            integralRecords = loadedRecords;
            updateTableFromCollection();
            JOptionPane.showMessageDialog(this, "Загружено " + loadedRecords.size() + " записей");
            
        } catch (IOException | NumberFormatException | InvalideRangeException ex) {
            JOptionPane.showMessageDialog(this, "Ошибка загрузки: " + ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1LoadtxtActionPerformed

    private void jMenuItem1LoadBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1LoadBinActionPerformed
    
        JFileChooser f = new JFileChooser();
        javax.swing.filechooser.FileNameExtensionFilter filter = 
            new javax.swing.filechooser.FileNameExtensionFilter("Binary file (*.ser)", "ser");
        f.setFileFilter(filter);
        f.showOpenDialog(this);
        
        File file = f.getSelectedFile();
        if (file == null) return;
        
        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream(file))) {
            integralRecords = (List<RecIntegral>) in.readObject();
            updateTableFromCollection();
            JOptionPane.showMessageDialog(this, "Загружено " + integralRecords.size() + " записей");
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Ошибка: " + ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1LoadBinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContactEditorUI().setVisible(true));
    }
//    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAdd1;
    private javax.swing.JButton jButtonAdd2;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1LoadBin;
    private javax.swing.JMenuItem jMenuItem1Loadtxt;
    private javax.swing.JMenuItem jMenuItem1SaveBin;
    private javax.swing.JMenuItem jMenuItem1SaveTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldFunction;
    private javax.swing.JTextField jTextFieldLowerInput;
    private javax.swing.JTextField jTextFieldLowerLabel;
    private javax.swing.JTextField jTextFieldStepInput;
    // End of variables declaration//GEN-END:variables
}

