/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sasha.pkg5a;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Александра
 */
public class ContactEditorUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContactEditorUI.class.getName());

    /**
     * Creates new form ContactEditorUI
     */
    public ContactEditorUI() {
    initComponents();
    
    // === НАЧАЛО ДОБАВЛЯЕМОГО КОДА ===
    
    // НАСТРОЙКА ТАБЛИЦЫ как в первой программе
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {
            "верхний предел", "нижний предел", "шаг", "результат"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
            true, true, true, false
        };
        
        @Override
        public Class getColumnClass(int columnIndex) {
            return types[columnIndex];
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };
    
    jTable1.setModel(model);
    
    // НАСТРОЙКА ЦВЕТОВ
    java.awt.Color buttonBg = new java.awt.Color(188, 179, 209);
    java.awt.Color textColor = new java.awt.Color(138, 134, 149);
    java.awt.Color fieldBg = new java.awt.Color(217, 207, 226);
    
    // Настройка полей ввода
    jTextFieldLowerLabel.setBackground(fieldBg);
    jTextFieldLowerLabel.setForeground(textColor);
    
    jTextFieldLowerInput.setBackground(fieldBg);
    jTextFieldLowerInput.setForeground(textColor);
    
    jTextFieldStepInput.setBackground(fieldBg);
    jTextFieldStepInput.setForeground(textColor);
    
    // Настройка кнопок
    jButtonAdd.setBackground(buttonBg);
    jButtonAdd.setForeground(textColor);
    jButtonAdd.setFocusPainted(false);
    
    jButtonSolve.setBackground(buttonBg);
    jButtonSolve.setForeground(textColor);
    jButtonSolve.setFocusPainted(false);
    
    jButtonDelete.setBackground(buttonBg);
    jButtonDelete.setForeground(textColor);
    jButtonDelete.setFocusPainted(false);
    
    // Настройка таблицы
    jTable1.setBackground(fieldBg);
    jTable1.setForeground(textColor);
    jTable1.setSelectionBackground(new java.awt.Color(220, 218, 237));
    jTable1.setGridColor(buttonBg);
    jTable1.setRowHeight(25);
    
    // === КОНЕЦ ДОБАВЛЯЕМОГО КОДА ===
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldFunction = new javax.swing.JTextField();
        jTextFieldLowerLabel = new javax.swing.JTextField();
        jTextFieldLowerInput = new javax.swing.JTextField();
        jTextFieldStepInput = new javax.swing.JTextField();
        jButtonSolve = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 218, 237));

        jPanel1.setBackground(new java.awt.Color(220, 218, 237));

        jTextFieldFunction.setBackground(new java.awt.Color(217, 207, 226));
        jTextFieldFunction.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFunction.setForeground(new java.awt.Color(138, 134, 149));
        jTextFieldFunction.setText("  cos(x)");
        jTextFieldFunction.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextFieldLowerInput.addActionListener(this::jTextFieldLowerInputActionPerformed);

        jTextFieldStepInput.addActionListener(this::jTextFieldStepInputActionPerformed);

        jButtonSolve.setBackground(new java.awt.Color(188, 179, 209));
        jButtonSolve.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSolve.setForeground(new java.awt.Color(138, 134, 149));
        jButtonSolve.setText("вычислить");
        jButtonSolve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSolve.setFocusPainted(false);
        jButtonSolve.addActionListener(this::jButtonSolveActionPerformed);

        jButtonAdd.setBackground(new java.awt.Color(188, 179, 209));
        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(138, 134, 149));
        jButtonAdd.setText("добавить");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.setFocusPainted(false);
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jButtonDelete.setBackground(new java.awt.Color(188, 179, 209));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(138, 134, 149));
        jButtonDelete.setText("удалить");
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.setFocusPainted(false);
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jLabel1.setBackground(new java.awt.Color(217, 207, 226));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(138, 134, 149));
        jLabel1.setText("Верхний предел");

        jLabel2.setBackground(new java.awt.Color(217, 207, 226));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(138, 134, 149));
        jLabel2.setText("Нижний предел");

        jLabel3.setBackground(new java.awt.Color(217, 207, 226));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(138, 134, 149));
        jLabel3.setText("Шаг");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldLowerInput, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jTextFieldLowerLabel)
                    .addComponent(jTextFieldStepInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSolve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTextFieldFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSolve)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLowerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStepInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        jTable1.setBackground(new java.awt.Color(217, 207, 226));
        jTable1.setForeground(new java.awt.Color(138, 134, 149));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "верхний предел", "нижний предел", "шаг", "результат"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(188, 179, 209));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(220, 218, 237));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLowerInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLowerInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLowerInputActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
                                          
    try {
        // Получаем значения из полей ввода
        String upperText = jTextFieldLowerLabel.getText();
        String lowerText = jTextFieldLowerInput.getText();
        String stepText = jTextFieldStepInput.getText();
        
        // Выводим значения в диалоговое окно
        String message = "Введенные значения:\n" +
                        "Верхний предел: " + upperText + "\n" +
                        "Нижний предел: " + lowerText + "\n" +
                        "Шаг: " + stepText;
        
        JOptionPane.showMessageDialog(this, message, "Введенные данные", JOptionPane.INFORMATION_MESSAGE);
        
        // Преобразуем строки в числа для дальнейшей обработки
        double upper = Double.parseDouble(upperText);
        double lower = Double.parseDouble(lowerText);
        double step = Double.parseDouble(stepText);
        
        // Проверка корректности данных
        if (step <= 0) {
            JOptionPane.showMessageDialog(this,
                "Шаг должен быть положительным!", "Ошибка",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (lower >= upper) {
            JOptionPane.showMessageDialog(this,
                "Нижний предел должен быть меньше верхнего!", "Ошибка",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Получаем модель таблицы
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        
        // Добавляем новую строку
        tModel.addRow(new Object[]{upper, lower, step, ""});
        
        // Очищаем поля ввода
        jTextFieldLowerLabel.setText("");
        jTextFieldLowerInput.setText("");
        jTextFieldStepInput.setText("");
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Введите корректные числа во все поля!", "Ошибка", 
            JOptionPane.ERROR_MESSAGE);
    }



    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed

    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow != -1) {
        int confirm = JOptionPane.showConfirmDialog(this,
            "Удалить выбранную строку?", "Подтверждение",
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
            tModel.removeRow(selectedRow);
        }
    } else {
        JOptionPane.showMessageDialog(this,
            "Выберите строку для удаления!", "Предупреждение",
            JOptionPane.WARNING_MESSAGE);
    }
    

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolveActionPerformed

    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow != -1) {
        try {
            // ВНИМАНИЕ: порядок колонок в таблице:
            // колонка 0: верхний предел (b)
            // колонка 1: нижний предел (a)
            // колонка 2: шаг
            double b = Double.parseDouble(jTable1.getValueAt(selectedRow, 0).toString()); // верхний
            double a = Double.parseDouble(jTable1.getValueAt(selectedRow, 1).toString()); // нижний
            double step = Double.parseDouble(jTable1.getValueAt(selectedRow, 2).toString()); // шаг
            
            // Метод трапеций для cos(x)
            int n = (int)((b - a) / step);
            if (n < 1) {
                JOptionPane.showMessageDialog(this,
                    "Слишком маленький интервал или большой шаг!", "Ошибка",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            double integral = 0;
            
            // Сумма средних точек
            for (int i = 1; i < n; i++) {
                double x = a + i * step;
                integral += Math.cos(x);
            }
            
            // Значения на границах
            double fa = Math.cos(a);
            double fb = Math.cos(b);
            
            // Последняя полная точка и остаток
            double lastFullX = a + n * step;
            double fLast = Math.cos(lastFullX);
            double lastStep = b - lastFullX;
            
            // Формула трапеций с учетом остатка
            if (Math.abs(lastStep) < 1e-10) {
                integral = (step / 2) * (fa + 2 * integral + fLast);
            } else {
                integral = (step / 2) * (fa + 2 * integral + fLast) + (lastStep / 2) * (fLast + fb);
            }
            
            // Выводим результат
            jTable1.setValueAt(String.format("%.6f", integral), selectedRow, 3);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Ошибка в данных строки! Проверьте числа.", "Ошибка",
                JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this,
            "Выберите строку для вычисления!", "Предупреждение",
            JOptionPane.WARNING_MESSAGE);
    }
    
    }//GEN-LAST:event_jButtonSolveActionPerformed

    private void jTextFieldStepInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStepInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStepInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContactEditorUI().setVisible(true));
    }
//    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldFunction;
    private javax.swing.JTextField jTextFieldLowerInput;
    private javax.swing.JTextField jTextFieldLowerLabel;
    private javax.swing.JTextField jTextFieldStepInput;
    // End of variables declaration//GEN-END:variables
}

